# Generated by Django 4.2.7 on 2023-12-17 07:28
from django.core.management import call_command
from django.db import migrations

def load_fixture(apps, schema_editor):
    call_command('loaddata', 'polls/fixture/db_init.json', app_label='polls')

class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_fixture),
    ]
